// Hide the 
$(function() {
    var pullDownMenuButton = $('#pullDownMenu');
    var menu = $('nav ul');

    $(pullDownMenuButton).on('click', function(clickEvent) {
        clickEvent.preventDefault();
        menu.slideToggle();
    });

    // Remove style generated by jQuery to redisplay menu if user resizes the screen
    $(window).resize(function() {
        var w = $(window).width();
        if (w > 600 && menu.is(':hidden')) {
            menu.removeAttr('style');
        }
    });
});
